godwin

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,76 +1,87 @@
-name: chocolatine
+name: Chocolatine
 on:
-  push:
-    branches-ignore:
-      - ga-ignore-*
-  pull_request:
-    branches-ignore:
-      - ga-ignore-*
-
+    push:
+        branches-ignore:
+        - "ga-ignore-*"
+    pull_request:
+        branches-ignore:
+        - "ga-ignore-*"
 env:
-  MIRROR_URL: "git@github.com:godlynjr/Minishell_2.git"
-  EXECUTABLES: "guess"
-
-
+  EXECUTABLES: my_sh
+  MIRROR_URL: git@github.com:EpitechPromo2027/B-PSU-200-COT-2-1-minishell1-godwin.bewa.git
 jobs:
   check_coding_style:
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - uses: actions/checkout@v3
-      - run: check.sh $(pwd) $(pwd)
-      - run: |
-          while read -r line; do
-            filename=$(echo "$line" | cut -d':' -f1)
-            line_number=$(echo "$line" | cut -d':' -f2)
-            error_type=$(echo "$line" | cut -d':' -f3)
-            error_code=$(echo "$line" | cut -d':' -f4)
-            echo "::error file=${filename##*/},line=$line_number,endLine=$line_number,title=$error_type coding style error,::$error_code"
-            done < coding-style-reports.log
-
+     - name: Checkout
+       uses: actions/checkout@v3
+       with:
+         fetch-depth: 0
+     - name: Coding Style Checker
+       run: check.sh $(pwd) $(pwd)
+     - name: Display errors
+       run: |
+         check.sh $(pwd) $(pwd)
+         cat coding-style-reports.log
+          if [[ -s $coding-style-reports.log ]]
+          then
+            exit 0
+          else
+            i=1
+            while read _r line
+            do
+            tab=( ${line//:/})
+            echo "::error::file=${tab[0]}, line=${tab[1]}, ::${tab[2]} coding style error:${tab[0]}#L${tab[1]}"
+              ((i++))
+              done < "coding-style-reports.log"
+            exit 1
+          fi
   check_program_compilation:
-    runs-on: ubuntu-latest
-    needs: [check_coding_style]
-    container: epitechcontent/epitest-docker
-    timeout-minutes: 2
-    steps:
-      - uses: actions/checkout@v3
-      - name: Checkout the code
-        uses: actions/checkout@v3
-      - name: Build the code
-        run: make
-      - name: Clean the code
-        run: make clean
-      - name: Check for executables
-        run: |
-          for exe in $(echo $EXECUTABLES | tr "," "\n"); do
-            if [ ! -x $exe ]; then
-              echo "Error: $exe not found or not executable"
-              exit 1
-            fi
-           done
-
-
+      needs:
+        - check_coding_style
+      runs-on: ubuntu-latest
+      container:
+        image: ghcr.io/epitech/coding-style-checker:latest
+      steps:
+        - name: Checkout2
+          uses: actions/checkout@v3
+          with:
+            fetch-depth: 0
+        - name: Compilation
+          run: make
+          timeout-minutes: 2
+        - name: Clean
+          run: make clean
+        - name: Verify executables
+          run: |
+           find -name "${{env.EXECUTABLES}}" | grep -q . && exit 0 || exit 1
   run_tests:
+    needs:
+      - check_program_compilation
     runs-on: ubuntu-latest
-    needs: [check_program_compilation]
-    container: epitechcontent/epitest-docker
-    timeout-minutes: 2
+    container:
+      image: epitechcontent/epitest-docker:latest
     steps:
-      - uses: actions/checkout@v3
-      - run: make tests_run
-
-
-  push_to_mirror:
-    runs-on: ubuntu-latest
-    needs: [run_tests]
-    if: github.event_name == 'push'
-    steps:
-      - uses: actions/checkout@v3
+      - name: Checkout3
+        uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1.0.1
+      - run: make tests_run
+        timeout-minutes: 2
+  push_to_mirror:
+    needs:
+      - run_tests
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout4
+        uses: actions/checkout@v3
         with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+          fetch_depth: 0
+      - name: Mirroring
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+           target_repo_url: ${{ env.MIRROR_URL }}
+           ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
