houcham

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,72 +1,76 @@
-name: Chocolatine
-
-env:
-  MIRROR_URL: git@github.com:EpitechPromo2027/B-CPE-101-COT-1-1-myprintf-mawunam.megnassan.git
-  EXECUTABLES: libmy.a
-
+name: chocolatine
 on:
   push:
     branches-ignore:
-      - 'ga-ignore-*'
+      - ga-ignore-*
   pull_request:
     branches-ignore:
-      - 'ga-ignore-*'
+      - ga-ignore-*
+
+env:
+  MIRROR_URL: "git@github.com:houcham00/tester.git"
+  EXECUTABLES: "day06"
+
 
 jobs:
   check_coding_style:
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
-    env:
-      SHERLOCKED: ${{ secrets.SHERLOCKED }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Run coding style checker
-        run: check.sh $(pwd) $(pwd) ${{ env.SHERLOCKED }}
-        continue-on-error: true
-      - name: Display errors
-        run: |
-          ERRORS=$(find . -type f -name ".c" -o -name ".h" -exec grep -n -H -E -e "^.:[[:space:]][[:graph:]]+[[:space:]]*$" {} \;)
-          if [ -n "$ERRORS" ]; then
-            echo "$ERRORS" | awk -F: '{printf "::error file=%s,line=%d::%s\n", $1, $2, $3}'
-            exit 1
-          fi
+      - uses: actions/checkout@v3
+      - run: check.sh $(pwd) $(pwd)
+      - run: |
+          while read -r line; do
+            filename=$(echo "$line" | cut -d':' -f1)
+            line_number=$(echo "$line" | cut -d':' -f2)
+            error_type=$(echo "$line" | cut -d':' -f3)
+            error_code=$(echo "$line" | cut -d':' -f4)
+            echo "::error file=${filename##*/},line=$line_number,endLine=$line_number,title=$error_type coding style error,::$error_code"
+            done < coding-style-reports.log
+
   check_program_compilation:
     runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker
-    timeout-minutes: 3
-    env:
-      SHERLOCKED: ${{ secrets.SHERLOCKED }}
+    needs: [check_coding_style]
+    container: epitechcontent/epitest-docker
+    timeout-minutes: 2
     steps:
-      - name: Checkout code
+      - uses: actions/checkout@v3
+      - name: Checkout the code
         uses: actions/checkout@v3
-      - name: Build code
+      - name: Build the code
         run: make
-      - name: Clean build
+      - name: Clean the code
         run: make clean
-        
+      - name: Check for executables
+        run: |
+          for exe in $(echo $EXECUTABLES | tr "," "\n"); do
+            if [ ! -x $exe ]; then
+              echo "Error: $exe not found or not executable"
+              exit 1
+            fi
+           done
+
+
   run_tests:
     runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker
-    timeout-minutes: 3
-    env:
-      SHERLOCKED: ${{ secrets.SHERLOCKED }}
+    needs: [check_program_compilation]
+    container: epitechcontent/epitest-docker
+    timeout-minutes: 2
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Run tests
-        run: make tests_run
+      - uses: actions/checkout@v3
+      - run: make tests_run
+
 
   push_to_mirror:
     runs-on: ubuntu-latest
+    needs: [run_tests]
+    if: github.event_name == 'push'
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1
+      - uses: pixta-dev/repository-mirroring-action@v1.0.1
         with:
           target_repo_url: ${{ env.MIRROR_URL }}
           ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
