Pawel

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,33 +1,56 @@
-name: Chocolatine
-
+name: chocolatine
 on:
-    push:
-      branches-ignore:
-        - "ga-ignore-*"
-    pull_request:
-      branches-ignore:
-        - "ga-ignore-*"
-env:
-  MIRROR_URL: git@github.com:EpitechPromo2027/B-MAT-100-COT-1-1-103cipher-horace.kougbla.git
-  EXECUTABLES: 103cipher
-
-jobs:
-      check_compilation:
-      runs-on: ubuntu-latest
-      container: epitechcontent/epitest-docker
-      needs: [check_coding_style]
-      steps:
-        - name: make_test
-          uses: actions/checkout@v3
-        - run:  make
-          timeout-minutes: 2
-        - run: |
-                if [[ -e $EXECUTABLES ]] && [[ -x $EXECUTABLES ]]
-                then
-                  exit 0
-                else
-                  exit 1
-                fi
-        - name: make_clean
-          uses: actions/checkout@v3
-        - run: make clean
+  push:
+  pull request:
+    branch ignore:
+      - 'ga-ignore-*'
+  jobs:
+  check:
+    runs-on: ubuntu-latest
+    step:
+      - name: check_branch_name
+        uses: actions/checkout@v2
+      - run: echo name is $GITHUB_ref
+     
+   check_coding_style:
+     runs-on: ubuntu-latest
+     container:
+        image: ghcr.io/epitech/coding-style-checker:latest
+    step:
+      - name: check_coding_style
+        uses: actions/setup-node@v3
+      - run: |
+           check.sh $(pwd) $(pwd)
+           cat coding-style-reports.log
+           if [[ -s $coding-style-report.log ]]
+           then
+             exit 0
+           else
+             i=1
+             while read -r line
+             do
+             tab=( ${line//:/})
+             echo "::error::file=${tab[0]}, line=${tab[1]}, ::${tab[2]} coding style error: ${tab[0]}#L${tab[1]}"
+               ((i++))
+               done < "coding-style-reports.log"
+             exit 1
+           fi
+         
+   check_program_compilation:
+     runs-on: ubuntu-latest
+     container:
+       image: epitechcontent/epitest-docker
+     steps:
+       - name: check_program_compilation
+         uses: actions/checkout@v2
+       - run: make
+       - run: make clean
+     
+   check_unit:
+     runs-on: ubuntu-latest
+     container:
+       image: epitechcontent/epitest-docker
+     steps:
+       - name: run_tests
+         uses: actions/checkout@v2
+       - run: make tests_ru
