florentin

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,87 +1,83 @@
 name: Chocolatine
+
 on:
-    push:
-        branches-ignore:
-        - "ga-ignore-*"
-    pull_request:
-        branches-ignore:
-        - "ga-ignore-*"
+  push:
+    branches-ignore:
+      - 'ga-ignore-* '
+  pull_request:
+    branches-ignore:
+      - 'ga-ignore-*'
+
 env:
-  EXECUTABLES: my_sh
-  MIRROR_URL: git@github.com:EpitechPromo2027/B-PSU-200-COT-2-1-minishell1-godwin.bewa.git
-jobs:
+  MIRROR_URL: git@github.com:EpitechPromo2027/B-CPE-110-COT-1-1-pushswap-florentin.ganfon.git
+  EXECUTABLES: push_wap
+
+jobs:  
   check_coding_style:
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
-     - name: Checkout
-       uses: actions/checkout@v3
-       with:
-         fetch-depth: 0
-     - name: Coding Style Checker
-       run: check.sh $(pwd) $(pwd)
-     - name: Display errors
-       run: |
-         check.sh $(pwd) $(pwd)
-         cat coding-style-reports.log
-          if [[ -s $coding-style-reports.log ]]
+      - name: check_coding_style
+        uses: actions/checkout@v3
+      - run : |
+          check.sh $(pwd) $(pwd)
+          cat coding-style-reports.log
+          if [ -s $coding-style-reports.log ]
+          i=0
           then
-            exit 0
-          else
-            i=1
-            while read _r line
-            do
-            tab=( ${line//:/})
-            echo "::error::file=${tab[0]}, line=${tab[1]}, ::${tab[2]} coding style error:${tab[0]}#L${tab[1]}"
+            while read -r line
+            do                                                                                                                                                                       
+              tab=( ${line//:/ } )
+              yo=(${tab[0]})
+              str=( ${yo//// } )
+              echo "::error file=${str[1]},line=${tab[3]},title=${tab[2]} coding style error::${tab[3]}"
               ((i++))
-              done < "coding-style-reports.log"
-            exit 1
+            done < "coding-style-reports.log"
           fi
+  
   check_program_compilation:
-      needs:
-        - check_coding_style
-      runs-on: ubuntu-latest
-      container:
-        image: ghcr.io/epitech/coding-style-checker:latest
-      steps:
-        - name: Checkout2
-          uses: actions/checkout@v3
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: [check_coding_style]
+    steps:
+      - name: make_test
+        uses: actions/checkout@v3
+      - run: make
+        timeout-minutes: 2
+      - run: |
+            if [[ -e $EXECUTABLES ]] && [[ -x $EXECUTABLES ]]
+            then
+              exit 0
+            else
+                exit 1
+            fi
+      - name: make_clean_test
+        uses: actions/checkout@v3
+      - run: make clean
+      
+  run_tests:
+    runs-on: ubuntu-latest
+    container: epitechcontent/epitest-docker
+    needs: [check_coding_style, check_program_compilation]
+    steps:
+      - name: run_tests
+        uses: actions/checkout@v3
+      - run:
+          make test run
+        timeout-minutes: 2
+          
+  push_to_mirror:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'push' }}
+    needs: [check_coding_style, check_program_compilation, run_tests]
+    steps:
+        - uses: actions/checkout@v3
           with:
             fetch-depth: 0
-        - name: Compilation
-          run: make
-          timeout-minutes: 2
-        - name: Clean
-          run: make clean
-        - name: Verify executables
-          run: |
-           find -name "${{env.EXECUTABLES}}" | grep -q . && exit 0 || exit 1
-  run_tests:
-    needs:
-      - check_program_compilation
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker:latest
-    steps:
-      - name: Checkout3
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - run: make tests_run
-        timeout-minutes: 2
-  push_to_mirror:
-    needs:
-      - run_tests
-    if: github.event_name == 'push'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout4
-        uses: actions/checkout@v3
-        with:
-          fetch_depth: 0
-      - name: Mirroring
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-           target_repo_url: ${{ env.MIRROR_URL }}
-           ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+        - uses: pixta-dev/repository-mirroring-action@v1
+          with:
+            target_repo_url:
+                ${{ env.MIRROR_URL }}
+            ssh_private_key:
+                ${{ secrets.GIT_SSH_PRIVATE_KEY }}
