florentin

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,76 +1,80 @@
-name: chocolatine
+name: Chocolatine
+
 on:
   push:
     branches-ignore:
-      - ga-ignore-*
+      - 'ga-ignore-* '
   pull_request:
     branches-ignore:
-      - ga-ignore-*
+      - 'ga-ignore-*'
 
 env:
-  MIRROR_URL: "git@github.com:godlynjr/Minishell_2.git"
-  EXECUTABLES: "mysh"
+  MIRROR_URL: git@github.com:EpitechPromo2027/B-CPE-110-COT-1-1-pushswap-florentin.ganfon.git
+  EXECUTABLES: guess
 
-
-jobs:
+jobs:  
   check_coding_style:
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - uses: actions/checkout@v3
-      - run: check.sh $(pwd) $(pwd)
-      - run: |
-          while read -r line; do
-            filename=$(echo "$line" | cut -d':' -f1)
-            line_number=$(echo "$line" | cut -d':' -f2)
-            error_type=$(echo "$line" | cut -d':' -f3)
-            error_code=$(echo "$line" | cut -d':' -f4)
-            echo "::error file=${filename##*/},line=$line_number,endLine=$line_number,title=$error_type coding style error,::$error_code"
-            done < coding-style-reports.log
-
+      - name: check_coding_style
+        uses: actions/checkout@v3
+      - run : |
+          check.sh $(pwd) $(pwd)
+          cat coding-style-reports.log
+          if [ -s $coding-style-reports.log ]
+          i=0
+          then
+            while read -r line
+            do                                                                                                                                                                       
+              tab=( ${line//:/ } )
+              yo=(${tab[0]})
+              str=( ${yo//// } )
+              echo "::error file=${str[1]},line=${tab[3]},title=${tab[2]} coding style error::${tab[3]}"
+              ((i++))
+            done < "coding-style-reports.log"
+          fi
+  
   check_program_compilation:
     runs-on: ubuntu-latest
-    needs: [check_coding_style]
     container: epitechcontent/epitest-docker
-    timeout-minutes: 2
     steps:
-      - uses: actions/checkout@v3
-      - name: Checkout the code
+      - name: make_test
         uses: actions/checkout@v3
-      - name: Build the code
-        run: make
-      - name: Clean the code
-        run: make clean
-      - name: Check for executables
-        run: |
-          for exe in $(echo $EXECUTABLES | tr "," "\n"); do
-            if [ ! -x $exe ]; then
-              echo "Error: $exe not found or not executable"
-              exit 1
+      - run: make
+        timeout-minutes: 2
+      - run: |
+            if [[ -e $EXECUTABLES ]] && [[ -x $EXECUTABLES ]]
+            then
+              exit 0
+            else
+                exit 1
             fi
-           done
-
-
+      - name: make_clean_test
+        uses: actions/checkout@v3
+      - run: make clean
+      
   run_tests:
     runs-on: ubuntu-latest
-    needs: [check_program_compilation]
     container: epitechcontent/epitest-docker
-    timeout-minutes: 2
     steps:
-      - uses: actions/checkout@v3
-      - run: make tests_run
-
-
+      - name: run_tests
+        uses: actions/checkout@v3
+      - run:
+          make test run
+        timeout-minutes: 2
+          
   push_to_mirror:
     runs-on: ubuntu-latest
-    needs: [run_tests]
-    if: github.event_name == 'push'
+    if: ${{ github.event_name == 'push' }}
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - uses: pixta-dev/repository-mirroring-action@v1.0.1
-        with:
-          target_repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+        - uses: actions/checkout@v3
+          with:
+            fetch-depth: 0
+        - uses: pixta-dev/repository-mirroring-action@v1
+          with:
+            target_repo_url:
+                ${{ env.MIRROR_URL }}
+            ssh_private_key:
+                ${{ secrets.GIT_SSH_PRIVATE_KEY }}
