Youvel

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,54 +1,58 @@
-name: Chocolatine
+name: chocolatine
 
 on:
   push:
+  pull_request:
     branches-ignore:
       - 'ga-ignore-*'
-  pull_request:
-  branches-ignore:
-      - 'ga-ignore-*'
-
-env:
-  MIRROR_URL: "git@github.com:EpitechPromo2027/B-MAT-100-COT-1-1-101pong-hodavia.bangbola.git"
-  EXECUTABLES: "101pong"
- 
+     
 jobs:
-  check_coding_style
+  check:
     runs-on: ubuntu-latest
-    container: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: check_branch_name
+        uses: actions/checkout@v2
+      - run: echo name is $GITHUB_REF
+       
+  check_coding_style:
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
     steps:
       - name: check_coding_style
         uses: actions/checkout@v3
-      - run: check.sh $(pwd) $(pwd)
-
-check_program_compilation      
-  runs-on: ubuntu-latest
-  container:  epitechcontent/epitest-docker
-  timeout-minutes: 2
-  steps:
-    - name: check_program_compilation
-      uses: actions/checkout@v3
-    - run: make
-    - name: Clean
-      uses: actions/checkout@v3
-    - run: make clean
- 
-run_tests
-        runs-on: ubuntu-latest
-        container: epitechcontent/epitest-docker
-        timeout-minutes: 2
-        steps:
-          - name: run_tests
-          uses: actions/checkout@v2
-          - name: xc_test
-          - run: make run_tests
-       
-push_to_mirror
-       runs-on: ubuntu-latest
-       if: github.event_name == 'push'
-       steps:
-         - name: push_to_mirror
-           uses: actions/checkout@v3
-         - name: push
-         - use: pixta-dev/repository-mirroring-action@v1
-         - with:
+      - run:
+          check.sh $(pwd) $(pwd)
+          cat coding-style-reports.log
+          if [[ -s $coding-style-reports.log ]]
+          then
+            exit 0
+          else
+            i=1
+            while read _r line
+            do
+            tab=( ${line//:/})
+            echo "::error::file=${tab[0]}, line=${tab[1]}, ::${tab[2]} coding style error:${tab[0]}#L${tab[1]}"
+              ((i++))
+              done < "coding-style-reports.log"
+            exit 1
+          fi
+     
+  check_program_compilation:
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker
+    steps:
+      - name: check_program_compilation
+        uses: actions/checkout@v2
+      - run: make
+      - run: make clean
+     
+  check_unit:
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker
+    steps:
+      - name: run_tests
+        uses: actions/checkout@v2
+      - run: make tests_run
